### GET secret application
http://localhost:5070/api/v1.0/secrets?secretName=examplesecret
Content-Type: application/json

### GET secret application bulk
http://localhost:5070/api/v1.0/secrets/bulk
Content-Type: application/json

### Get secret dapr api
http://localhost:3570/v1.0/secrets/secretstore/examplesecret
Content-Type: application/json

### GET secret bulk dapr api
http://localhost:3570/v1.0/secrets/secretstore/bulk
Content-Type: application/json