### State store GET application
GET http://localhost:5070/api/v1.0/state-store
Content-Type: application/json

### State store GET with eTag application
GET http://localhost:5070/api/v1.0/state-store/etag
Content-Type: application/json

### State store DELETE application
DELETE http://localhost:5070/api/v1.0/state-store
Content-Type: application/json

### State store PUT application
PUT http://localhost:5070/api/v1.0/state-store
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "age": 30
}

### State store POST application
POST http://localhost:5070/api/v1.0/state-store
Content-Type: application/json

{
  "eTag": "123456",
  "stateStore": 
  {
    "firstName": "Max",
    "lastName": "Mustermann",
    "age": 35
  }
}

### State store GET dapr api 
GET http://localhost:3570/v1.0/state/statestore/123456
Content-Type: application/json

### State store DELTE dapr api
DELETE http://localhost:3570/v1.0/state/statestore/123456
Content-Type: application/json

### State store POST dapr api
POST http://localhost:3570/v1.0/state/statestore
Content-Type: application/json

[
  {
    "eTag": "1",
    "key": "123456",
    "value": {
      "firstName": "Max",
      "lastName": "Mustermann",
      "age": 45
    }
  }
]


### Query State Store POST dapr api
POST http://localhost:3570/v1.0/state/querystore
Content-Type: application/json

[
  {
    "key": "1",
    "value": {
      "firstName": "Max",
      "lastName": "Mustermann",
      "age": 45
    }
  },
  {
    "key": "2",
    "value": {
      "firstName": "Peter",
      "lastName": "Pan",
      "age": 20
    }
  },
  {
    "key": "3",
    "value": {
      "firstName": "John",
      "lastName": "Doe",
      "age": 50
    }
  }
]

### Filter state GET by name application
GET http://localhost:5070/api/v1.0/state-store/filter-by-name
Content-Type: application/json

### Query State Store filter by name - dapr api
POST http://localhost:3570/v1.0-alpha1/state/querystore/query?metadata.contentType=application/json
Content-Type: application/json

{
  "filter": {
    "EQ": {
      "firstName": "Max"
    }
  }
}

### Sort by name application
GET http://localhost:5070/api/v1.0/state-store/sort-by-age
Content-Type: application/json

### Query State Store sort by age - dapr api
POST http://localhost:3570/v1.0-alpha1/state/querystore/query?metadata.contentType=application/json
Content-Type: application/json

{
  "sort": [
    {
      "key": "age",
      "order": "DESC"
    }
  ]
}

### Page application
GET http://localhost:5070/api/v1.0/state-store/page
Content-Type: application/json

### Query State Store page - dapr api
POST http://localhost:3570/v1.0-alpha1/state/querystore/query?metadata.contentType=application/json
Content-Type: application/json

{
  "page": {
    "limit": 1
  }
}

### Query State Store page token 1 - dapr api
POST http://localhost:3570/v1.0-alpha1/state/querystore/query?metadata.contentType=application/json
Content-Type: application/json

{
  "page": {
    "limit": 1,
    "token": "1"
  }
}



